server {
    listen 80;
    server_name __DOMAIN__;

    root /home/__USER__/public_html;
    index index.html index.php;

    access_log /var/log/nginx/__DOMAIN___access.log;
    error_log /var/log/nginx/__DOMAIN___error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
